SERVICE_ROUTES = {
    "/api/users": "http://user-service:8000/users/",
    "/api/auth": "http://auth-service:5003/auth/",
    "/api/auth/login": "http://auth-service:5003/auth/login/",
    "/api/auth/register": "http://auth-service:5003/auth/register/",
    "/api/auth/refresh": "http://auth-service:5003/auth/refresh/",
    "/api/auth/swagger": "http://auth-service:5003/swagger/",
    "/api/auth/redoc": "http://auth-service:5003/redoc/",
    "/api/departements": "http://departement-service:5005/departements/",
    "/api/courses": "http://course-service:5006/courses/",
    "/api/delivered-times": "http://courier-time-service:5007/delivered-times/",
    "/api/conges": "http://conge-service:5008/conges/",
    "/api/soldes": "http://soldes-service:5009/soldes/",
    "/api/prets": "http://pret-service:5010/prets/",
}
