SERVICE_ROUTES = {
    "/api/backend": "http://web:8000/",
    "/api/config": "http://config-service:5000/",
    "/api/users": "http://user-service:5002/users/",
    "/api/auth": "http://auth-service:5003/auth/",
    "/api/auth/login": "http://auth-service:5003/auth/login/",
    "/api/auth/register": "http://auth-service:5003/auth/register/",
    "/api/auth/refresh": "http://auth-service:5003/auth/refresh/",
    "/api/auth/swagger": "http://auth-service:5003/swagger/",
    "/api/auth/redoc": "http://auth-service:5003/redoc/",
    "/api/feedback-users": "http://feedback-user:5001/feedback-users/",
    "/api/avances": "http://avance-service:5004/avances/",
    "/api/demandes": "http://avance-service:5004/avances/",
    "/api/attestations": "http://attestation-service:5011/attestations/",
    "/api/departements": "http://departement-service:5005/departements/",
    "/api/courses": "http://course-service:5006/courses/",
    "/api/delivered-times": "http://courier-time-service:5007/delivered-times/",
    "/api/conges": "http://conge-service:5008/conges/",
    "/api/soldes": "http://soldes-service:5009/soldes/",
    "/api/prets": "http://pret-service:5010/prets/",
}
